-- generated by kon
hl.config({
    general = {
        gaps_in = 4,
        gaps_out = 8,
        border_size = 2,
        col = {
            active_border = "rgba(3a8ee6ff)",
            inactive_border = "rgba(8ea6c0ff)",
        },
    },
    decoration = {
        rounding = 6,
        inactive_opacity = 0.8,
        blur = {
            enabled = true,
            size = 6,
            passes = 3,
        },
        shadow = {
            enabled = true,
            range = 12,
            render_power = 3,
            color = "rgba(1b263355)",
        },
    },
})
