#!/usr/bin/env python3
"""kon - the aero theme for aro, Hyprland and niri: colours, shape and motion in every app.

    kon                 apply it (also: kon aero)
    kon restore         put back the theme's wallpaper (for aro's exec)

The theme is ~/.config/kon/themes/aero.json and the app templates are in
templates/; edit either and run kon again.
"""

import json
import os
import re
import subprocess
import sys
from pathlib import Path

HOME = Path.home()
CONF = HOME / ".config"
KON = CONF / "kon"
THEMES = KON / "themes"
CACHE = HOME / ".cache"
os.environ["PATH"] = f"{HOME}/.local/bin:{os.environ.get('PATH', '')}"

SHAPE = {"radius": 5, "border_width": 2, "gaps": 9, "outer_gaps": 9, "bar_height": 30, "opacity": 0.92,
         "header_gloss": 0.0, "header_opacity": 1.0}
MOTION = {"speed": 1.0, "bounce": 1.0}


def sh(*cmd):
    subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + ".kon-tmp")
    tmp.write_text(text)
    tmp.replace(path)


def rgb(h):
    return ", ".join(str(int(h[i:i + 2], 16)) for i in (0, 2, 4))


def flatten(tid, t):
    # everything the templates need
    p = dict(t["colors"])
    p.update(dict(SHAPE, **t.get("shape", {})))
    p.update(dict(MOTION, **t.get("motion", {})))
    p["theme"] = tid
    p["cache"] = str(CACHE)
    p["name"] = t.get("name", tid)
    p["tagline"] = t.get("tagline", "")
    p["layout"] = "aero"
    p["cursor"] = t.get("cursor", "")   # empty keeps the user's cursor
    wp = t.get("wallpaper")
    p["wallpaper"] = str(Path(os.path.expanduser(wp)).resolve()) if wp else ""
    p["gaps_half"] = max(0, round(p["gaps"] / 2))   # Hyprland's gaps_in is per side
    p["frame_rgb"] = rgb(p["frame"])
    p["accent_rgb"] = rgb(p["accent"])
    return p


def load(tid):
    return flatten(tid, json.loads((THEMES / f"{tid}.json").read_text()))


def render(template, p):
    return re.sub(r"\{\{(\w+)\}\}", lambda m: str(p[m.group(1)]), template)


# apps

def templated(p, names=("mako", "swaylock", "fuzzel.ini")):
    targets = {
        "mako": CONF / "mako/config",
        "swaylock": CONF / "swaylock/config",
        "fuzzel.ini": CONF / "fuzzel/fuzzel.ini",
    }
    for name in names:
        write(targets[name], render((KON / "templates" / name).read_text(), p))


ARO_COLOURS = {
    "background": lambda p: p["background"] + "ff",
    "frame": lambda p: p["frame"] + "ff",
    "frame_focus": lambda p: p["frame_focus"] + "ff",
    "border_color": lambda p: p["border"] + "ff",
    "accent": lambda p: p["accent"] + "ff",
    "accent_soft": lambda p: p["accent"] + "4d",
    "text": lambda p: p["text"] + "ff",
    "text_dim": lambda p: p["dim"] + "ff",
    "bar_color": lambda p: p["bar"] + "ff",
    "urgent": lambda p: p["urgent"] + "ff",
    "drop_fill": lambda p: p["accent"] + "1f",
    "drop_line": lambda p: p["accent"] + "cc",
}

# aro's animation times at speed 1
ARO_MOTION = {"anim_ms": 340, "fullscreen_anim_ms": 220, "focus_anim_ms": 160,
              "drop_anim_ms": 160, "workspace_slide_ms": 220}


def aro(p):
    path = CONF / "aro/config"
    if not path.exists():
        return
    s = path.read_text()
    for key, val in ARO_COLOURS.items():
        s = re.sub(rf"^(\s*{key}\s*=\s*)(0x|#)?[0-9a-fA-F]{{6,8}}", lambda m: m.group(1) + "0x" + val(p),
                   s, flags=re.M)
    nums = {"radius": p["radius"], "border": p["border_width"], "gaps": p["gaps"], "outer_gaps": p["outer_gaps"]}
    nums.update({k: max(1, round(v / max(0.1, p["speed"]))) for k, v in ARO_MOTION.items()})
    for key, val in nums.items():
        s = re.sub(rf"^(\s*{key}\s*=\s*)\d+(\.\d+)?", lambda m: m.group(1) + str(int(val)), s, flags=re.M)
    # only touch these if they're already there
    for key in ("header_gloss", "header_opacity"):
        s = re.sub(rf"^(\s*{key}\s*=\s*)\d+(\.\d+)?", lambda m: m.group(1) + f"{float(p[key]):g}", s, flags=re.M)
    if "exec = kon restore" not in s:
        s = s.replace("# ── keyboard", "# kon: the current theme's wallpaper, see ~/.config/kon\nexec = kon restore\n\n# ── keyboard", 1)
    write(path, s)


def hypr(p):
    # kon-aero.lua does require("kon")
    if (CONF / "hypr/kon-aero.lua").exists():
        write(CONF / "hypr/kon.lua", render((KON / "templates/hypr-kon.lua").read_text(), p))


def niri(p):
    # config.kdl does include "kon.kdl"
    if (CONF / "niri/config.kdl").exists():
        write(CONF / "niri/kon.kdl", render((KON / "templates/niri-kon.kdl").read_text(), p))


def foot(p):
    a = p["ansi"]
    alpha = min(1.0, max(0.3, round(p["opacity"] - 0.07, 2)))
    out = ["# generated by kon", "", "[colors-dark]",
           f"foreground={p['text']}", f"background={p['background']}", f"alpha={alpha}", "blur=yes"]
    out += [f"regular{i}={a[i]}" for i in range(8)] + [f"bright{i}={a[i + 8]}" for i in range(8)]
    out += [f"selection-foreground={p['on_accent']}", f"selection-background={p['accent']}",
            f"cursor={p['background']} {p['accent']}", f"urls={p['accent']}",
            f"jump-labels={p['on_accent']} {p['accent']}", ""]
    write(CONF / "foot/themes/kon", "\n".join(out))
    path = CONF / "foot/foot.ini"
    s = path.read_text()
    s = re.sub(r"^include=.*themes/\w+$", "include=~/.config/foot/themes/kon", s, flags=re.M)
    s = re.sub(r"^\[colors-dark\]\n(?:(?!\[).*\n?)*", "", s, flags=re.M)
    s = re.sub(r"^initial-color-theme=.*\n", "", s, flags=re.M)
    write(path, s)
    terminals(p)


def terminals(p):
    # recolour open terminals, like pywal
    a = p["ansi"]
    seq = "".join(f"\033]4;{i};#{a[i]}\033\\" for i in range(16))
    seq += (f"\033]10;#{p['text']}\033\\\033]11;#{p['background']}\033\\\033]12;#{p['accent']}\033\\"
            f"\033]17;#{p['accent']}\033\\\033]19;#{p['on_accent']}\033\\")
    data = seq.encode()
    uid = os.getuid()
    for pts in Path("/dev/pts").glob("[0-9]*"):
        try:
            if pts.stat().st_uid != uid:
                continue
            fd = os.open(pts, os.O_WRONLY | os.O_NOCTTY | os.O_NONBLOCK)
            try:
                os.write(fd, data)
            finally:
                os.close(fd)
        except OSError:
            pass


def gtk(p):
    a = p["accent"]
    css = f"""/* generated by kon */
@define-color accent_color #{a};
@define-color accent_bg_color #{a};
@define-color accent_fg_color #{p['on_accent']};
@define-color destructive_bg_color #{p['urgent']};
@define-color destructive_fg_color #{p['on_accent']};
@define-color error_bg_color #{p['urgent']};
@define-color error_fg_color #{p['on_accent']};
@define-color window_bg_color #{p['frame']};
@define-color window_fg_color #{p['text']};
@define-color view_bg_color #{p['background']};
@define-color view_fg_color #{p['text']};
@define-color headerbar_bg_color #{p['frame_focus']};
@define-color headerbar_fg_color #{p['text']};
@define-color headerbar_backdrop_color @window_bg_color;
@define-color popover_bg_color #{p['frame_focus']};
@define-color popover_fg_color #{p['text']};
@define-color card_bg_color #{p['frame_focus']};
@define-color card_fg_color #{p['text']};
@define-color dialog_bg_color #{p['frame']};
@define-color dialog_fg_color #{p['text']};
@define-color sidebar_bg_color #{p['bar']};
@define-color sidebar_fg_color #{p['text']};
@define-color sidebar_backdrop_color @sidebar_bg_color;
@define-color sidebar_border_color #{p['border']};
@define-color secondary_sidebar_bg_color #{p['frame']};
@define-color secondary_sidebar_fg_color #{p['text']};
@define-color theme_selected_bg_color @accent_bg_color;
@define-color theme_selected_fg_color @accent_fg_color;
@define-color theme_unfocused_fg_color @window_fg_color;
@define-color theme_unfocused_text_color @view_fg_color;
@define-color theme_unfocused_bg_color @window_bg_color;
@define-color theme_unfocused_base_color @window_bg_color;
@define-color theme_unfocused_selected_bg_color @accent_bg_color;
@define-color theme_unfocused_selected_fg_color @accent_fg_color;
"""
    root = f""":root {{
    --accent-color: #{a};
    --accent-bg-color: #{a};
    --accent-fg-color: #{p['on_accent']};
    --destructive-bg-color: #{p['urgent']};
    --destructive-fg-color: #{p['on_accent']};
    --error-bg-color: #{p['urgent']};
    --error-fg-color: #{p['on_accent']};
    --error-color: #{p['urgent']};
    --window-bg-color: #{p['frame']};
    --window-fg-color: #{p['text']};
    --view-bg-color: #{p['background']};
    --view-fg-color: #{p['text']};
    --headerbar-bg-color: #{p['frame_focus']};
    --headerbar-fg-color: #{p['text']};
    --popover-bg-color: #{p['frame_focus']};
    --popover-fg-color: #{p['text']};
    --card-bg-color: #{p['frame_focus']};
    --card-fg-color: #{p['text']};
    --dialog-bg-color: #{p['frame']};
    --dialog-fg-color: #{p['text']};
    --sidebar-bg-color: #{p['bar']};
    --sidebar-fg-color: #{p['text']};
    --warning-color: #{p['ansi'][3]};
    --success-color: #{p['ansi'][2]};
    --window-radius: {max(p['radius'], 1) * 2}px;
}}
"""
    write(CONF / "gtk-3.0/kon.css", css)
    write(CONF / "gtk-4.0/kon.css", css + root)
    for d in ("gtk-3.0", "gtk-4.0"):
        f = CONF / d / "gtk.css"
        if f.exists() and 'import url("kon.css")' not in f.read_text():
            f.replace(f.with_name("gtk.css.pre-kon"))
        write(f, '/* generated by kon, the old one is gtk.css.pre-kon */\n@import url("kon.css");\n')


def btop(p):
    a = p["ansi"]
    keys = {
        "main_bg": p["background"], "main_fg": p["text"], "title": p["accent"], "hi_fg": p["accent"],
        "selected_bg": p["frame_focus"], "selected_fg": p["accent"], "inactive_fg": p["dim"],
        "proc_misc": p["accent2"], "cpu_box": p["border"], "mem_box": p["border"],
        "net_box": p["border"], "proc_box": p["border"], "div_line": p["border"],
        "temp_start": a[6], "temp_mid": a[3], "temp_end": a[1],
        "cpu_start": p["accent2"], "cpu_mid": p["accent"], "cpu_end": p["urgent"],
        "free_start": a[8], "free_mid": a[2], "free_end": a[10],
        "cached_start": a[8], "cached_mid": a[4], "cached_end": a[12],
        "available_start": a[8], "available_mid": a[6], "available_end": a[14],
        "used_start": p["accent2"], "used_mid": p["accent"], "used_end": p["urgent"],
        "download_start": a[8], "download_mid": a[4], "download_end": a[12],
        "upload_start": a[8], "upload_mid": a[5], "upload_end": a[13],
    }
    body = "\n".join(f'theme[{k}]="#{v}"' for k, v in keys.items())
    write(CONF / "btop/themes/kon.theme", f"# generated by kon\n\n{body}\n")
    path = CONF / "btop/btop.conf"
    if path.exists():
        write(path, re.sub(r'^color_theme = ".*"$', 'color_theme = "kon"', path.read_text(), flags=re.M))


def cava(p):
    write(CONF / "cava/themes/kon", f"""# generated by kon
[color]
foreground = '#{p['accent']}'

gradient = 1
gradient_color_1 = '#{p['accent2']}'
gradient_color_2 = '#{p['accent']}'
gradient_color_3 = '#{p['text']}'
""")
    path = CONF / "cava/config"
    if path.exists():
        write(path, re.sub(r'^theme = ".*"$', 'theme = "kon"', path.read_text(), flags=re.M))
    sh("pkill", "-USR2", "-x", "cava")


def starship(p):
    a = p["ansi"]
    cols = {
        "blue": a[4], "red": a[1], "green": a[2], "yellow": a[3], "cyan": a[6], "magenta": a[5],
        "white": p["text"], "black": a[0], "rosewater": p["accent2"], "flamingo": a[9], "pink": a[13],
        "mauve": a[5], "maroon": a[1], "peach": p["accent2"], "teal": a[6], "sky": a[14],
        "sapphire": a[12], "lavender": a[13], "text": p["text"], "subtext1": p["text"],
        "subtext0": p["dim"], "overlay2": p["dim"], "overlay1": p["dim"], "overlay0": p["border"],
        "surface2": p["border"], "surface1": p["frame_focus"], "surface0": p["frame"],
        "base": p["background"], "mantle": p["bar"], "crust": p["bar"],
        "accent": p["accent"],
    }
    block = "# >>> kon\n[palettes.kon]\n" + "".join(f'{k} = "#{v}"\n' for k, v in cols.items()) + "# <<< kon\n"
    path = CONF / "starship.toml"
    if not path.exists():
        return
    s = path.read_text()
    s = re.sub(r'^palette = ".*"$', 'palette = "kon"', s, count=1, flags=re.M)
    if "# >>> kon" in s:
        s = re.sub(r"# >>> kon.*?# <<< kon\n", lambda m: block, s, flags=re.S)
    else:
        s = s.rstrip("\n") + "\n\n" + block
    write(path, s)


def fastfetch(p):
    path = CONF / "fastfetch/config.jsonc"
    try:
        cfg = json.loads(path.read_text())
    except (OSError, ValueError):
        return
    cfg.setdefault("display", {})["color"] = {"keys": "#" + p["accent"], "title": "#" + p["accent2"]}
    cfg["display"].setdefault("percent", {})["color"] = {"green": "#" + p["ansi"][2],
                                                           "yellow": "#" + p["ansi"][3],
                                                           "red": "#" + p["urgent"]}
    write(path, json.dumps(cfg, indent=2) + "\n")


def qutebrowser(p):
    bg, fg, fr, ff, bd = (f"#{p[k]}" for k in ("background", "text", "frame", "frame_focus", "border"))
    ac, dim, on, urg = f"#{p['accent']}", f"#{p['dim']}", f"#{p['on_accent']}", f"#{p['urgent']}"
    pairs = {
        "completion.fg": fg, "completion.odd.bg": fr, "completion.even.bg": fr,
        "completion.category.fg": ac, "completion.category.bg": bg,
        "completion.category.border.top": bg, "completion.category.border.bottom": bg,
        "completion.item.selected.fg": on, "completion.item.selected.bg": ac,
        "completion.item.selected.border.top": ac, "completion.item.selected.border.bottom": ac,
        "completion.item.selected.match.fg": on, "completion.match.fg": ac,
        "completion.scrollbar.fg": dim, "completion.scrollbar.bg": fr,
        "contextmenu.menu.bg": fr, "contextmenu.menu.fg": fg,
        "contextmenu.selected.bg": ac, "contextmenu.selected.fg": on,
        "downloads.bar.bg": bg, "downloads.start.bg": dim, "downloads.stop.bg": ac,
        "downloads.error.bg": urg,
        "hints.bg": ac, "hints.fg": on, "hints.match.fg": fg,
        "keyhint.bg": fr, "keyhint.fg": fg, "keyhint.suffix.fg": ac,
        "messages.error.bg": urg, "messages.error.fg": on, "messages.error.border": urg,
        "messages.warning.bg": fr, "messages.warning.fg": ac, "messages.warning.border": ac,
        "messages.info.bg": fr, "messages.info.fg": fg, "messages.info.border": bd,
        "prompts.bg": fr, "prompts.fg": fg, "prompts.border": f"{p['border_width']}px solid {ac}",
        "prompts.selected.bg": ac, "prompts.selected.fg": on,
        "statusbar.normal.bg": bg, "statusbar.normal.fg": fg,
        "statusbar.insert.bg": ac, "statusbar.insert.fg": on,
        "statusbar.passthrough.bg": f"#{p['accent2']}", "statusbar.passthrough.fg": on,
        "statusbar.command.bg": bg, "statusbar.command.fg": fg,
        "statusbar.url.fg": fg, "statusbar.url.success.http.fg": fg,
        "statusbar.url.success.https.fg": ac, "statusbar.url.hover.fg": ac,
        "statusbar.url.error.fg": urg, "statusbar.url.warn.fg": f"#{p['accent2']}",
        "statusbar.progress.bg": ac,
        "tabs.bar.bg": bg, "tabs.odd.bg": bg, "tabs.even.bg": bg, "tabs.odd.fg": dim, "tabs.even.fg": dim,
        "tabs.selected.odd.bg": ff, "tabs.selected.even.bg": ff,
        "tabs.selected.odd.fg": ac, "tabs.selected.even.fg": ac,
        "tabs.indicator.start": f"#{p['accent2']}", "tabs.indicator.stop": ac, "tabs.indicator.error": urg,
        "webpage.bg": bg,
    }
    lines = ["# generated by kon"]
    lines += [f"c.colors.{k} = {v!r}" for k, v in pairs.items()]
    write(CONF / "qutebrowser/kon.py", "\n".join(lines) + "\n")
    wall = p["wallpaper"] or subprocess.run(["kon-wm", "wallpaper"], capture_output=True, text=True).stdout.strip()
    write(KON / "start.html", render((KON / "templates/start-aero.html").read_text(), dict(p, wallpaper=wall)))
    if subprocess.run(["pgrep", "-f", "bin/qutebrowser"], stdout=subprocess.DEVNULL).returncode == 0:
        sh("qutebrowser", ":config-source")


def shared(p):
    # the shell reads this
    keys = ("theme", "name", "tagline", "wallpaper", "background", "bar", "frame", "frame_focus",
            "border", "text", "dim", "accent", "accent2", "on_accent", "urgent", "ansi",
            "radius", "border_width", "gaps", "outer_gaps", "bar_height", "opacity", "speed", "bounce", "layout")
    data = json.dumps({k: p[k] for k in keys}, indent=2) + "\n"
    write(CACHE / "kon/palette.json", data)
    write(CACHE / "aroclip/theme.json", data)


def wallpaper(p):
    if p["wallpaper"] and Path(p["wallpaper"]).is_file():
        sh("kon-wm", "wallpaper", p["wallpaper"])


GTK_SETTINGS = (CONF / "gtk-3.0/settings.ini", CONF / "gtk-4.0/settings.ini")


def cursor_installed(name):
    dirs = (HOME / ".local/share/icons", HOME / ".icons", Path("/usr/share/icons"))
    return any((d / name / "cursors").is_dir() for d in dirs)


def set_cursor(aro_value, gtk, gs):
    path = CONF / "aro/config"
    s = path.read_text() if path.exists() else ""
    if re.search(r"^\s*cursor_theme\s*=", s, re.M):
        s = re.sub(r"^(\s*cursor_theme\s*=\s*).*$", lambda m: m.group(1) + aro_value, s, count=1, flags=re.M)
        write(path, s)
    for f, name in gtk.items():
        f = Path(f)
        if f.exists() and name:
            write(f, re.sub(r"^gtk-cursor-theme-name=.*$", "gtk-cursor-theme-name=" + name,
                            f.read_text(), flags=re.M))
    if gs:
        sh("gsettings", "set", "org.gnome.desktop.interface", "cursor-theme", gs)


def cursor(p):
    name = p["cursor"]
    if name and cursor_installed(name):
        quoted = f"'{name}'" if " " in name else name
        set_cursor(quoted, {str(f): name for f in GTK_SETTINGS}, name)



def apply():
    p = load("aero")
    cursor(p)
    shared(p)
    aro(p)
    hypr(p)
    niri(p)
    sh("kon-wm", "reload")
    foot(p)
    templated(p)
    sh("makoctl", "reload")
    gtk(p)
    btop(p)
    cava(p)
    starship(p)
    fastfetch(p)
    qutebrowser(p)
    wallpaper(p)
    sh("qs", "-c", "aroclip", "ipc", "call", "kon", "changed", "aero", p["name"], p["tagline"])
    print(f"{p['name']}: {p['tagline']}")


def main():
    arg = sys.argv[1] if len(sys.argv) > 1 else "aero"
    if arg in ("aero", "apply"):
        apply()
    elif arg == "restore":
        wallpaper(load("aero"))
    else:
        print(__doc__.strip(), file=sys.stderr)
        return 2
    return 0

if __name__ == "__main__":
    sys.exit(main())
