-- generated by kon
hl.config({
    general = {
        gaps_in = {{gaps_half}},
        gaps_out = {{outer_gaps}},
        border_size = {{border_width}},
        col = {
            active_border = "rgba({{accent}}ff)",
            inactive_border = "rgba({{border}}ff)",
        },
    },
    decoration = {
        rounding = {{radius}},
        inactive_opacity = 0.8,
        blur = {
            enabled = true,
            size = 6,
            passes = 3,
        },
        shadow = {
            enabled = true,
            range = 12,
            render_power = 3,
            color = "rgba(1b263355)",
        },
    },
})
